malloc nits
ava-labs/avalanchego pull request #1307
Opened 2023-04-07 18:17 UTC by danlaine

## Why this should be merged

Avoid memory allocations where possible

## How this works

Pretty straighforward -- see my comments

## How this was tested

Existing UT

2023-04-07 18:19 UTC, danlaine commented on vms/avm/utxo/spender.go
> +		ins          = []*avax.TransferableInput(nil)
`ins` and `keys` are returned so they escape to the heap

2023-04-07 18:37 UTC, StephenButtolph commented
I know for some of these we explicitly used empty slices (rather than `nil` slices) because `json` marshalling treats them differently and we wanted `[]` in the json rather than `null`.

2023-04-07 19:11 UTC, danlaine commented
> I know for some of these we explicitly used empty slices (rather than `nil` slices) because `json` marshalling treats them differently and we wanted `[]` in the json rather than `null`.
> 
> Admittedly we are extremely inconsistent here... But we should really just decide what we are trying to do.

Up to you what you want to do with respect to the JSON marshalling

2023-04-07 19:12 UTC, danlaine commented
Is there anyone downstream that would be affected by us using `null` rather than `[]` in JSON?

2023-04-07 20:10 UTC, StephenButtolph commented
> Is there anyone downstream that would be affected by us using `null` rather than `[]` in JSON?

javascript treats them differently - so changing these may be a breaking change.

2023-04-10 20:11 UTC, abi87 commented on vms/nftfx/mint_operation.go
> +	outs := make([]verify.State, len(op.Outputs))
q: isn't marginally better to preallocate capacity only (`make([]verify.State,0, len(op.Outputs))`) and then append new element? I wonder if `make([]verify.State, len(op.Outputs))` waste time allocating default values

2023-04-10 20:14 UTC, abi87 commented on vms/platformvm/utxo/handler.go
> +		ins          = []*avax.TransferableInput(nil)
q: I believe most of p-chain txs do consume inputs (I assume e.g. import/export are the most common, but I may be wrong). If this is true wouldn't be more efficient to allocate ins as we currently do? (Getting an estimate for capacity would be great too)

2023-04-10 20:15 UTC, abi87 requested changes
just a few questions, mainly around how can we be sure that avoiding preallocation is more efficient than allocating (even with zero capacity)

2023-06-01 13:37 UTC, closed without merging