vms/platformvm/service: nits (preallocate address slice, error msg)
ava-labs/avalanchego pull request #1477
Opened 2023-05-05 01:05 UTC by gyuho

## Why this should be merged

bytes to string conversion never fails, if formatting encoding fails, it should be from the encoding format.

## How this works

Accurate error message.

## How this was tested

N/A

2023-05-05 04:02 UTC, dhrubabasu commented on vms/platformvm/service.go
> +		Addresses: make([]string, 0, len(owner.Addrs)),
we should modify `apiOwner.Addresses = append(apiOwner.Addresses, addrStr)` to take advantage of this preallocation

2023-05-05 04:02 UTC, dhrubabasu requested changes
One nit

2023-05-05 04:11 UTC, dhrubabasu approved these changes

2023-05-06 10:44 UTC, StephenButtolph approved these changes

2023-05-06 10:45 UTC, merged