utils/bag: print generic type for bag elements
ava-labs/avalanchego pull request #1507
Opened 2023-05-15 04:15 UTC by gyuho

## Why this should be merged

Better debug-ability when we print the type of the generic bag

## How this works

Add `%T` in stringer method

## How this was tested

```go
func TestBagStringer(t *testing.T) {
	bag := Bag[ids.ID]{}

	elt0 := ids.GenerateTestID()
	elt1 := ids.GenerateTestID()
	elt2 := ids.GenerateTestID()

	bag.AddCount(elt0, 1)
	bag.AddCount(elt1, 2)
	bag.AddCount(elt2, 3)

	fmt.Println(bag.String())
}
```

```
➜  bag git:(bag-types) go test -v -run TestBagStringer
=== RUN   TestBagStringer
Bag: (Size = 6)
    Zda4gsqTjRaX6XVZekVNi3ovMFPHDRQiGbzYuAb7Nwqy1rGBc: 3
    2mcwQKiD8VEspmMJpL1dc7okQQ5dDVAWeCBZ7FWBFAbxpv3t7w: 2
    TtF4d2QWbk5vzQGTEPrN48x6vwgAoAmKQ9cbp79inpQmcRKES: 1
--- PASS: TestBagStringer (0.00s)
PASS
ok      github.com/ava-labs/avalanchego/utils/bag       0.092s
➜  bag git:(bag-types) ✗ go test -v -run TestBagStringer
=== RUN   TestBagStringer
Bag[ids.ID]: (Size = 6)
    2mcwQKiD8VEspmMJpL1dc7okQQ5dDVAWeCBZ7FWBFAbxpv3t7w: 2
    TtF4d2QWbk5vzQGTEPrN48x6vwgAoAmKQ9cbp79inpQmcRKES: 1
    Zda4gsqTjRaX6XVZekVNi3ovMFPHDRQiGbzYuAb7Nwqy1rGBc: 3
--- PASS: TestBagStringer (0.00s)
PASS
ok      github.com/ava-labs/avalanchego/utils/bag       0.253s
```

2023-05-16 16:02 UTC, dhrubabasu commented on utils/bag/bag.go
> +	sb.WriteString(fmt.Sprintf("Bag[%T]: (Size = %d)", *new(T), b.Len()))
We should use `utils.Zero[T]()`: https://github.com/ava-labs/avalanchego/blob/master/utils/zero.go#L7-L9

2023-05-16 16:02 UTC, dhrubabasu requested changes
one nit

2023-05-18 02:22 UTC, gyuho commented on utils/bag/unique_bag.go
> +	sb.WriteString(fmt.Sprintf("UniqueBag[%T]: (Size = %d)", *new(T), len(*b)))
Ah, nice!

2023-05-18 02:24 UTC, dhrubabasu approved these changes

2023-05-18 15:55 UTC, StephenButtolph approved these changes

2023-05-18 16:58 UTC, merged