e2e: Diagnose and fix flakes
ava-labs/avalanchego pull request #1941
Opened 2023-08-29 17:33 UTC by marun

## Why this should be merged

The high incidence of e2e flakes suggests a need to increase the details logged in testing to aid in diagnosing failure. Also, tests are made more resilient to failure.

## How this works

 - Enable the wallet to accept an optional function to log a transaction ID immediately after issuance and ensure the e2e wallet helper configures the wallet with the option. 
 - Log the node ID used by a given test
   - Also ensure that tests use at most one node (where possible) to minimize the scope of log inspection
 - Resolve C-Chain flakes induced by (https://github.com/ava-labs/coreth/issues/314) by doubling the suggested gas price

## How this was tested

CI on this PR and on PRs based on it: 
 - #1767 
 - #1792
 - #1882

2023-08-31 19:59 UTC, danlaine requested changes

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/c/interchain_workflow.go
> +		nodeURI := e2e.Env.GetRandomNodeURI()
Nit: can we move this just above its usage on line 48

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/e2e.go
> +	"github.com/ava-labs/avalanchego/ids"
nit
```suggestion
	"golang.org/x/exp/maps"

	"github.com/ava-labs/coreth/core/types"
	"github.com/ava-labs/coreth/ethclient"
	"github.com/ava-labs/coreth/interfaces"

	"github.com/ava-labs/avalanchego/ids"
```

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/e2e.go
> +	tests.Outf("{{blue}} initializing a new wallet for URI: %s {{/}}\n", uri)
Should we log the node ID too?

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/e2e.go
> +	tests.Outf("{{blue}} initializing a new eth client for URI: %s {{/}}\n", nodeURI)
Should we log the node ID too?

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/e2e.go
> +// of a transaction being submitted but failing to be accepted.
nit
```suggestion
// Log's [tx]'s ID if it's non-nil. Should be called before checking
// for an error to ensure traceability in the event of a transaction
// being submitted but failing to be accepted.
```

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/e2e.go
> +// if an error occurred.
```suggestion
// Log's [tx]'s ID if it's non-nil and asserts [err] is nil.
```

2023-08-31 19:59 UTC, danlaine commented on tests/e2e/e2e.go
> +func SendEthTransaction(ethClient ethclient.Client, signedTx *types.Transaction) *types.Receipt {
Should we have this function take in a context? Not strictly necessary but might be nice for it to be cancellable

2023-08-31 19:59 UTC, danlaine commented on tests/fixture/testnet/local/network.go
>  		// Only append URIs that are not empty. A node may have an
idk exactly what "loaded" in this method's comment means, but is it an issue that we may not return a map that contains all of the nodes in this network?

2023-09-05 18:10 UTC, danlaine commented on wallet/subnet/primary/common/options.go
> +func (o *Options) LogTxIDFunc() LogTxIDFunc {
Having this as on option feels kind of weird to me. Maybe we could have a more general `OnIssued` callback or something?

2023-09-05 18:17 UTC, danlaine commented on tests/e2e/c/interchain_workflow.go
> +			_ = e2e.SendEthTransaction(ethClient, signedTx)
Why do we ignore this error?

2023-09-05 19:56 UTC, danlaine commented on tests/e2e/e2e.go
> +				tests.Outf(" tx id: %s\n", id)
Should this say "issuing tx id" for log readability?

2023-09-05 19:56 UTC, danlaine approved these changes

2023-09-07 00:05 UTC, StephenButtolph approved these changes

2023-09-07 00:05 UTC, StephenButtolph commented on tests/e2e/e2e.go
> +	// Retrieve the contract address
This comment seems incorrect

2023-09-07 01:01 UTC, merged