make `rpcchainvm` die on SIGINT
ava-labs/avalanchego pull request #1953
Opened 2023-08-31 19:37 UTC by danlaine

## Why this should be merged

Makes signal handling same as avalanchego

## How this works

self-explanatory

## How this was tested

n/a

2023-08-31 19:39 UTC, danlaine commented on vms/rpcchainvm/vm.go
> -		for {
We return on receipt of any any of the handled signals or context cancellation so no need for loop

2023-08-31 19:39 UTC, danlaine commented on vms/rpcchainvm/vm.go
> -				switch s {
We only handle `SIGINT` and `SIGTERM` and both are handled the same way so no need for switch

2023-08-31 20:02 UTC, anusha-ctrl approved these changes
Tested locally on ANR. SIGTERM sent to avalanchego processes ends all chains gracefully.

2023-08-31 20:24 UTC, StephenButtolph commented
> Makes signal handling same as avalanchego

I don't think the goal was for this logic to be the same as avalanchego.

2023-08-31 21:54 UTC, StephenButtolph requested changes
I'm unable to replicate the bug that this is supposed to be fixing. Can we add some more detailed testing instructions?

2023-09-05 21:08 UTC, hexfusion commented
I believe the problem with supporting `SIGINT` is ctrl-c sends `SIGINT` to both the main process and the subprocess. This results in the same condition as systemd. We ran into this bug on the first iteration of go-plugin removal. 

ref https://github.com/ava-labs/avalanchego-internal/pull/2682

2023-09-05 21:10 UTC, hexfusion commented
cc @ceyonur

2023-09-05 22:01 UTC, closed without merging

2023-09-05 22:01 UTC, StephenButtolph commented
Closing this - as it seems like it would re-introduce a regression