Use `t.Cleanup()`
ava-labs/avalanchego pull request #2491
Opened 2023-12-15 19:20 UTC by dhrubabasu

## Why this should be merged

We currently require consumers of `newEnvironment` to call `shutdownEnvironment`. We can use `t.Cleanup()` to do this more robustly and save on LoC.

## How this works

Deletes `shutdownEnvironment` and moves it to a `t.Cleanup` call

## How this was tested

CI

2023-12-15 19:36 UTC, abi87 requested changes
I'd suggest to move these changes after we cleaned up the UTs framework.
As you know there is quite some code duplication currently and a few PRs have been open for a few months now to address this. You can find them in https://github.com/ava-labs/avalanchego/issues/2453. You know I welcome your review on those.
Merging these PRs will result in a larger reduction of LOC than any ad-hoc attempt like this one. It would also definitely reduce the work needed to maintain those PRs up to date

2023-12-18 19:08 UTC, dhrubabasu commented
> I'd suggest to move these changes after we cleaned up the UTs framework. As you know there is quite some code duplication currently and a few PRs have been open for a few months now to address this. You can find them in #2453. You know I welcome your review on those. Merging these PRs will result in a larger reduction of LOC than any ad-hoc attempt like this one. It would also definitely reduce the work needed to maintain those PRs up to date

Where does this PR overlap with the UT framework PRs? I'd be happy to update those PRs if that unblocks this minor cleanup PR.

2023-12-18 22:07 UTC, abi87 commented
> > I'd suggest to move these changes after we cleaned up the UTs framework. As you know there is quite some code duplication currently and a few PRs have been open for a few months now to address this. You can find them in #2453. You know I welcome your review on those. Merging these PRs will result in a larger reduction of LOC than any ad-hoc attempt like this one. It would also definitely reduce the work needed to maintain those PRs up to date
> 
> Where does this PR overlap with the UT framework PRs? I'd be happy to update those PRs if that unblocks this minor cleanup PR (or minimize the diff here if it reduces conflicts)

It's not so much the effort of rebasing the PRs in https://github.com/ava-labs/avalanchego/issues/2453, but to do it daily in order to keep them up to date. Same actually applies to all the outstanding P-chain PRs.
This PR helps maintanability of P-chain UTs, which is not great at the moment. The whole https://github.com/ava-labs/avalanchego/issues/2453 thread does, and it tries to tackle:

- removal of code duplication across packages
- bittle handling of fork times and ordering

I am suggesting to prioritize these PRs by impact and to merge PRs in https://github.com/ava-labs/avalanchego/issues/2453 before this ones

2023-12-27 15:18 UTC, danlaine approved these changes

2024-01-19 16:59 UTC, abi87 approved these changes

2024-01-19 21:00 UTC, StephenButtolph approved these changes

2024-01-19 21:15 UTC, merged